### ISSUE TITLE
Change Application ID

### ISSUE THREAD

**Issue by weather-kr** [CoraLibre/CoraLibre-android#10]
Currently the same application ID is used for the Corona-Warn-App and the CoraLibre app (de.rki.coronawarnapp). This prevents the installation of CoraLibre on a Device, where the Corona Warn App already runs.

With a unique name it is possible to run both Apps in parallel.

Changing the ID is possible with a single line change in file "Corona-Warn-App/build.gradle". I have successfully installed the pached CoraLibre app on a "Nokia 5.1 Plus" device in parallel to the original Corona-Warn-App. The error message without patch was:
"Du kannst die App auf deinem Gerät nicht installieren".

**Comment by theScrabi** [comment]
Yes the I'd declared [here](https://github.com/CoraLibre/CoraLibre-android/blob/638e5ae135cc7fb48e34ba2c93314e866d201280/Corona-Warn-App/build.gradle#L33) should be changed.
I'd suggest something like `de.coralibre.Coralibre`

@BjoernPetersen please have a look at this.

**Comment by BjoernPetersen** [comment]
Incidentally I had already changed that locally last week, just didn't push it 😄. I went with `de.coralibre.app` because I wanted to differentiate it from the SDK, but it's not like the SDK is going to clash with the app somewhere.

Which app ID would you prefer @theScrabi? `de.coralibre.app` or `de.coralibre.coralibre` (they should be lower-case, like package names).

**Comment by theScrabi** [comment]
I think its just about the appid ... Would that id really colide with the sdk? I thought a library cant have an id.

**Comment by theScrabi** [comment]
The scheme is "toplevel.organisation.appname". Simply " app" may not fit this scheme, however other than this i would go with ".app" just as well.

**Comment by BjoernPetersen** [comment]
No, it won't collide (you may have misread my previous comment on that). I'll go with `de.coralibre.coralibre` then.
