### ISSUE TITLE
Collaboration with "cwa-android"?

### ISSUE THREAD

**Issue by beerisgood** [CoraLibre/CoraLibre-android#13]
German Corona App without proprietary Google libraries
https://codeberg.org/corona-contact-tracing-germany/cwa-android

related:
https://github.com/corona-warn-app/cwa-app-android/issues/1483#issuecomment-734491614

**Comment by beerisgood** [comment]
> the fork from https://codeberg.org/corona-contact-tracing-germany/cwa-android seems to work fine, and will hit the F-Droid repo this week (hopefully) 😃

https://github.com/corona-warn-app/cwa-app-android/issues/75#issuecomment-735935002

**Comment by 1Maxnet1** [comment]
Is there a reason, why you don't join forces with the Corona Contact Tracing Germany App? It is already available in the F-Droid repository and ready for daily use, so why doubling the effort and not instead join forces ?

You mentioned already, that development is stalled so maybe it would make sense to merge the current codebase and mark this project as archived then?

**Comment by beerisgood** [comment]
@CoraLibre
