### ISSUE TITLE
Replace app imprint

### ISSUE THREAD

**Issue by BjoernPetersen** [CoraLibre/CoraLibre-android#8]
The imprint found in the app has not been updated yet and needs to be replaced.

**Comment by Stypox** [comment]
What is an app's imprint?

**Comment by BjoernPetersen** [comment]
The German word would be "Impressum"

**Comment by Stypox** [comment]
@BjoernPetersen I don't think you meant to close this, did you?

**Comment by BjoernPetersen** [comment]
No, I didn't. It seems the issue with the same ID from upstream has been closed by one of the upstream commits I just merged... Thanks for catching that!
